language: java
jdk:
  - openjdk8
install:
  - mvn test-compile -DskipTests=true -Dmaven.javadoc.skip=true -B -V
script:
  - mvn org.jacoco:jacoco-maven-plugin:prepare-agent test org.jacoco:jacoco-maven-plugin:report
after_success:
  - mvn org.eluder.coveralls:coveralls-maven-plugin:report
cache:
  directories:
  - $HOME/.m2
notifications:
  email: false
